language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master

after_success:
  - test "$TRAVIS_BRANCH" == "master" && ./gradlew uploadArchives -PsigningPassword='${signingPassword}'
  -PpublishUser='${publishUser}' -PpublishPassword='${publishPassword}'