language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master

after_success:
  - test "$TRAVIS_BRANCH" == "master" && ./gradlew uploadArchives -PsigningPassword="${SIGNING_PASSWORD}" -PpublishUser="${PUBLISH_USER}" -PpublishPassword="${PUBLISH_PASSWORD}"