language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master

after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ]; then ./gradlew uploadArchives -PsigningPassword="${SIGNING_PASSWORD}" -PpublishUser="${PUBLISH_USER}" -PpublishPassword="${PUBLISH_PASSWORD}"; fi