language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then uploadArchives -PsigningPassword='${signingPassword}' -PpublishUser='${publishUser}' -PpublishPassword='${publishPassword}'